# permissions for end users to view sops.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sop-viewer-role
rules:
- apiGroups:
  - app.integreatly.org
  resources:
  - sops
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.integreatly.org
  resources:
  - sops/status
  verbs:
  - get
